name: Run doctest on interpreter mode codes

on:
  push:
    branches:
      - main
    paths:
      - source/**
      - .github/workflows/doctest.yml

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

  doctest:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        chapter:
          - 1-numbers-and-strings
    steps:
      - id: chapter
        run: |
          files=$(find source/03-getting-started/${{ matrix.chapter }} -type f -name "[1-9]-*.rst.txt" | sort)
          echo "::set-output name=files::${files//$'\n'/\ }"
      - name: Prepare chapter doctest target
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          sources: ${{ steps.chapter.outputs.files }}
          destination: source/${{ matrix.chapter }}.rst.txt
      - name: Run doctest in chapter
        run: python -m doctest -v source/${{ matrix.chapter }}.rst.txt
