name: Run doctest on interpreter mode codes

on:
  push:
    branches:
      - main
    paths:
      - source/**
      - .github/workflows/doctest.yml

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

  doctest-with-matrix:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        chapter:
          - 1-numbers-and-strings
          - 2-variables
          - 3-1-use-functions
          - 3-2-input-output
          - 3-3-define-functions
          - 4-in-order
          - 5-fork
          - 6-loop
          - 7-1-list
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: chapter
        run: |
          files=$(find source/03-getting-started/${{ matrix.chapter }} -type f -name "[1-9]-*.rst.txt" | sort)
          echo "::set-output name=files::${files//$'\n'/\ }"
      - name: Prepare chapter doctest target
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          sources: ${{ steps.chapter.outputs.files }}
          destination: source/${{ matrix.chapter }}.rst.txt
      - name: Run doctest in chapter
        run: python -m doctest -v source/${{ matrix.chapter }}.rst.txt

  doctest-programming_practice:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: chapter
        run: |
          files=$(find source/03-getting-started/7-2-programmer-thinking -type f -name "[1-9]-*.rst.txt" | sort)
          echo "::set-output name=files::${files//$'\n'/\ }"
      - name: Prepare chapter doctest target
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          sources: ${{ steps.chapter.outputs.files }}
          destination: source/390-programmer_thinking/codes/7-2/sut.rst.txt
      - name: Run doctest in chapter
        run: |
          # doctestの実行中に aisatsu.py をimportできるように配置する
          cd source/390-programmer_thinking/codes/7-2
          python -m doctest -v sut.rst.txt
